export const GET_CURRENT_NOTEBOOK = 'GET_CURRENT_NOTEBOOK';
export const GET_CURRENT_NOTEBOOK_SUCCESS = 'GET_CURRENT_NOTEBOOK_SUCCESS';
export const GET_CURRENT_NOTEBOOK_FAILURE = 'GET_CURRENT_NOTEBOOK_FAILURE';
